<?php
$service = array(
    array(
        'エレベーター保守',
        '我々Buyingは、中小企業のコスト適正我々Buyingは、
        中小企業のコスト適正化の経我々Buyingは、中小企業のコ中小企業のコ
        中小企業のコ中小企業のコ',
        'http://www.naver.com',
        'm_service1.png'
    ),
    array(
        '電気料金削減',
        '我々Buyingは、中小企業のコスト適正我々Buyingは、
        中小企業のコスト適正化の経我々Buyingは、中小企業のコ中小企業のコ
        中小企業のコ中小企業のコ',
        'http://www.naver.com',
        'm_service2.png'
    ),
    array(
        '食材共同購買',
        '我々Buyingは、中小企業のコスト適正我々Buyingは、
        中小企業のコスト適正化の経我々Buyingは、中小企業のコ中小企業のコ
        中小企業のコ中小企業のコ',
        'http://www.naver.com',
        'm_service3.png'
    ),
);

$strong = array(
    array(
        'コスト削減商材の多さ',
        '人件費以外のすべての費用削減可能',
        'http://www.naver.com'
    ),
    array(
        '「交渉」削減という独自の費用削減手法',
        'Buying会員ネットワークを利用した共同購買',
        'http://www.naver.com'
    ),
    array(
        '支払いリスク完全排除',
        '完全成果型報酬制度',
        'http://www.naver.com'
    ),
);

$cost_down = array(
    array(
        '悩みその１',
        '売り上げが頭打ちになっている…。
        資金繰りが正直厳しい…。'
    ),
    array(
        '悩みその２',
        '大手の購買単価で購入したいけど、自社の購買量じゃ、
        正直これ以上の単価交渉は厳しい…。'
    ),
    array(
        '悩みその3',
        '何年も前からコスト適正化は行っているし自信はある！
        と思っているけれど本当に適正だろうか…。'
    ),
    array(
        '悩みその4',
        '制度変更は市場変化に対応できず何をすれば
        いいか正直わからない…。'
    ),
);